testing without some steps

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -25,12 +25,11 @@ jobs:
               uses: actions/setup-node@v3
               with:
                 node-version: ${{matrix.node-version}}
-            - name: Fail if experimental
-              if: ${{matrix.tag == 'experimental'}}
-              run: exit 1
+            # - name: Fail if experimental
+            #   if: ${{matrix.tag == 'experimental'}}
+            #   run: exit 1
             - name: Perform some tests
               run: |
-                sleep 10
                 echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
             - name: Upload test results
               run: echo Uploading test results
